import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Bootstrap from "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";

//import "bootstrap/dist/js/bootstrap.bundle.min.js";

import Navbar from "./components/navbar";
import NavbarB from "./components/navbarB";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <NavbarB />
        {children}
        <Footer />
      </body>
    </html>
  );
}
